spring.application.name=noctua-backend

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/noctua}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

jwt.secret=${JWT_SECRET:noctuaSecretKeyForJwtSigningMustBe256BitsLongAtLeast!}
jwt.expiration-ms=86400000
jwt.expiration-ms-extended=2592000000